-- 코드를 입력하세요
SELECT DISTINCT CART_ID
FROM CART_PRODUCTS cp1
WHERE NAME = 'Milk' 
    AND EXISTS (
    SELECT 1
    FROM CART_PRODUCTS cp2
    WHERE cp2.CART_ID = cp1.CART_ID
    AND cp2.NAME = 'Yogurt')
ORDER BY CART_ID;