SELECT YEAR(o.SALES_DATE) AS YEAR, MONTH(o.SALES_DATE) AS MONTH, 
        COUNT(DISTINCT u.USER_ID) AS PUCHASED_USERS, 
        ROUND(COUNT(DISTINCT u.USER_ID)/(
        SELECT COUNT(DISTINCT u.USER_ID)
        FROM USER_INFO u
        WHERE u.JOINED BETWEEN '2021-01-01' AND '2021-12-31'
    ),1) AS PUCHASED_RATIO
FROM ONLINE_SALE o JOIN USER_INFO u ON o.USER_ID=u.USER_ID
WHERE u.JOINED BETWEEN '2021-01-01' AND '2021-12-31'
GROUP BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE)
ORDER BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE)
